site_name: "BAM Data Store Documentation"
site_description: |
  Documentation for the schema of Simulation data.
site_author: BAM
repo_url: https://github.com/JosePizarro3/BAM-DataStore-Documentation
nav:
  - Home: index.md
  - Tutorial:
    - Tutorial 1: tutorials/1.md
    - Tutorial 1: tutorials/2.md
  - How-to guides:
    - How-to blabla: howtos/1.md
    - How-to bleble: howtos/2.md
  - Explanations:
    - Data Store: explanations/data-store.md
    - OpenBIS : explanations/openbis.md
    - pyBIS : explanations/pybis.md
  - References:
    - Collection: references/collection.md
    - Controlled Vocabulary: references/controlled-vocabulary.md
    - Dataset: references/dataset.md
theme:
  name: material
  palette:
    primary: "#2A4CDF"
    accent: "#008A67"
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default
    #   toggle:
    #     icon: material/weather-sunny
    #     name: Switch to dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   toggle:
    #     icon: material/weather-night
    #     name: Switch to light mode
  font:
    text: "Titillium Web"
  logo: assets/favicon.png
  favicon: assets/favicon.png
  features:
    - navigation.path
    - navigation.footer
    - navigation.top
  icon:
    repo: fontawesome/brands/github
plugins:
  - search
  # - bibtex:
      # bib_file: docs/assets/refs.bib
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: True
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/js-yaml/4.1.0/js-yaml.min.js'
  - 'https://unpkg.com/cytoscape@3.19.1/dist/cytoscape.min.js'
extra:
  version: 0.1
  generator: false
